config/routes.rb
Rails.application.routes.draw do
  resources :sql_templates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sql_template.rb
class SqlTemplate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sql_templates_controller.rb
class SqlTemplatesController < ApplicationController
  before_action :set_sql_template, only: [:show, :edit, :update, :destroy]

  # GET /sql_templates
  # GET /sql_templates.json
  def index
    @sql_templates = SqlTemplate.all
  end

  # GET /sql_templates/1
  # GET /sql_templates/1.json
  def show
  end

  # GET /sql_templates/new
  def new
    @sql_template = SqlTemplate.new
  end

  # GET /sql_templates/1/edit
  def edit
  end

  # POST /sql_templates
  # POST /sql_templates.json
  def create
    @sql_template = SqlTemplate.new(sql_template_params)

    respond_to do |format|
      if @sql_template.save
        format.html { redirect_to @sql_template, notice: 'Sql template was successfully created.' }
        format.json { render :show, status: :created, location: @sql_template }
      else
        format.html { render :new }
        format.json { render json: @sql_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sql_templates/1
  # PATCH/PUT /sql_templates/1.json
  def update
    respond_to do |format|
      if @sql_template.update(sql_template_params)
        format.html { redirect_to @sql_template, notice: 'Sql template was successfully updated.' }
        format.json { render :show, status: :ok, location: @sql_template }
      else
        format.html { render :edit }
        format.json { render json: @sql_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sql_templates/1
  # DELETE /sql_templates/1.json
  def destroy
    @sql_template.destroy
    respond_to do |format|
      format.html { redirect_to sql_templates_url, notice: 'Sql template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sql_template
      @sql_template = SqlTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sql_template_params
      params.require(:sql_template).permit(:body, :path, :format, :locale, :handler, :partial)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sql_templates_helper.rb
module SqlTemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Templater</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sql_templates/_form.html.erb
<%= form_for(sql_template) do |f| %>
  <% if sql_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sql_template.errors.count, "error") %> prohibited this sql_template from being saved:</h2>

      <ul>
      <% sql_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path %>
  </div>

  <div class="field">
    <%= f.label :format %>
    <%= f.text_field :format %>
  </div>

  <div class="field">
    <%= f.label :locale %>
    <%= f.text_field :locale %>
  </div>

  <div class="field">
    <%= f.label :handler %>
    <%= f.text_field :handler %>
  </div>

  <div class="field">
    <%= f.label :partial %>
    <%= f.check_box :partial %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sql_templates/edit.html.erb
<h1>Editing Sql Template</h1>

<%= render 'form', sql_template: @sql_template %>

<%= link_to 'Show', @sql_template %> |
<%= link_to 'Back', sql_templates_path %>

app/views/sql_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sql Templates</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Path</th>
      <th>Format</th>
      <th>Locale</th>
      <th>Handler</th>
      <th>Partial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sql_templates.each do |sql_template| %>
      <tr>
        <td><%= sql_template.body %></td>
        <td><%= sql_template.path %></td>
        <td><%= sql_template.format %></td>
        <td><%= sql_template.locale %></td>
        <td><%= sql_template.handler %></td>
        <td><%= sql_template.partial %></td>
        <td><%= link_to 'Show', sql_template %></td>
        <td><%= link_to 'Edit', edit_sql_template_path(sql_template) %></td>
        <td><%= link_to 'Destroy', sql_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sql Template', new_sql_template_path %>

app/views/sql_templates/new.html.erb
<h1>New Sql Template</h1>

<%= render 'form', sql_template: @sql_template %>

<%= link_to 'Back', sql_templates_path %>

app/views/sql_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @sql_template.body %>
</p>

<p>
  <strong>Path:</strong>
  <%= @sql_template.path %>
</p>

<p>
  <strong>Format:</strong>
  <%= @sql_template.format %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @sql_template.locale %>
</p>

<p>
  <strong>Handler:</strong>
  <%= @sql_template.handler %>
</p>

<p>
  <strong>Partial:</strong>
  <%= @sql_template.partial %>
</p>

<%= link_to 'Edit', edit_sql_template_path(@sql_template) %> |
<%= link_to 'Back', sql_templates_path %>